/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  Meeting: () => import('#controllers/meeting_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Recordings: () => import('#controllers/recordings_controller'),
  Transcriptions: () => import('#controllers/transcriptions_controller'),
}
