/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MeetingSchema extends BaseModel {
  static $columns = ['createdAt', 'createdBy', 'description', 'scheduledAt', 'status', 'tenantId', 'title', 'updatedAt', 'uuid'] as const
  $columns = MeetingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: string
  @column()
  declare description: string | null
  @column.dateTime()
  declare scheduledAt: DateTime
  @column()
  declare status: string
  @column()
  declare tenantId: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class RecordingSchema extends BaseModel {
  static $columns = ['createdAt', 'duration', 'fileName', 'fileUrl', 'meetingId', 'mimeType', 'size', 'status', 'tenantId', 'updatedAt', 'uuid'] as const
  $columns = RecordingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare duration: number | null
  @column()
  declare fileName: string | null
  @column()
  declare fileUrl: string | null
  @column()
  declare meetingId: string
  @column()
  declare mimeType: string | null
  @column()
  declare size: number | null
  @column()
  declare status: string
  @column()
  declare tenantId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'name', 'predefined', 'slug', 'status', 'tenantId', 'updatedAt', 'uuid'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare name: string
  @column()
  declare predefined: boolean | null
  @column()
  declare slug: string
  @column()
  declare status: string | null
  @column()
  declare tenantId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class TenantSchema extends BaseModel {
  static $columns = ['createdAt', 'name', 'status', 'updatedAt', 'uuid'] as const
  $columns = TenantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare status: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class TranscriptionSchema extends BaseModel {
  static $columns = ['aiActions', 'aiKeyPoints', 'aiSummary', 'audioUrl', 'createdAt', 'language', 'meetingId', 'provider', 'recordingId', 'status', 'summary', 'tenantId', 'text', 'updatedAt', 'uuid'] as const
  $columns = TranscriptionSchema.$columns
  @column()
  declare aiActions: any | null
  @column()
  declare aiKeyPoints: any | null
  @column()
  declare aiSummary: string | null
  @column()
  declare audioUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare language: string
  @column()
  declare meetingId: string
  @column()
  declare provider: string | null
  @column()
  declare recordingId: string
  @column()
  declare status: string
  @column()
  declare summary: string | null
  @column()
  declare tenantId: string
  @column()
  declare text: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class UserHasRoleSchema extends BaseModel {
  static $columns = ['roleId', 'userId'] as const
  $columns = UserHasRoleSchema.$columns
  @column()
  declare roleId: string
  @column({ isPrimary: true })
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['color', 'companyName', 'createdAt', 'email', 'fullName', 'locale', 'password', 'phone', 'status', 'tenantId', 'updatedAt', 'uuid', 'verified'] as const
  $columns = UserSchema.$columns
  @column()
  declare color: string
  @column()
  declare companyName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare locale: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare phone: string | null
  @column()
  declare status: string | null
  @column()
  declare tenantId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
  @column()
  declare verified: boolean
}
