/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime()
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime()
  declare updatedAt: DateTime | null
}

export class MeetingSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'createdBy',
    'duration',
    'language',
    'processedAt',
    'status',
    'startedAt',
    'stoppedAt',
    'tenantId',
    'title',
    'updatedAt',
    'uuid',
  ] as const
  $columns = MeetingSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime | null
  @column()
  declare createdBy: string | null
  @column()
  declare duration: number | null
  @column()
  declare language: string
  @column.dateTime()
  declare processedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime()
  declare startedAt: DateTime | null
  @column.dateTime()
  declare stoppedAt: DateTime | null
  @column()
  declare tenantId: string | null
  @column()
  declare title: string | null
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class ModelHasUploadSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'modelId', 'updatedAt', 'uploadId'] as const
  $columns = ModelHasUploadSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare modelId: string
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare uploadId: string | null
}

export class UploadSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'fileName',
    'filePath',
    'fileSize',
    'fileType',
    'mimeType',
    'originalName',
    'updatedAt',
    'uploadedBy',
    'uuid',
  ] as const
  $columns = UploadSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime | null
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column()
  declare fileSize: number
  @column()
  declare fileType: string
  @column()
  declare mimeType: string
  @column()
  declare originalName: string
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare uploadedBy: string
  @column({ isPrimary: true })
  declare uuid: string
}

export class RoleSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'description',
    'name',
    'predefined',
    'slug',
    'status',
    'tenantId',
    'updatedAt',
    'uuid',
  ] as const
  $columns = RoleSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare name: string
  @column()
  declare predefined: boolean | null
  @column()
  declare slug: string
  @column()
  declare status: string | null
  @column()
  declare tenantId: string
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class TenantSchema extends BaseModel {
  static $columns = ['createdAt', 'name', 'status', 'updatedAt', 'uuid'] as const
  $columns = TenantSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare status: string | null
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class TranscriptionSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'language',
    'meetingId',
    'provider',
    'status',
    'tenantId',
    'text',
    'updatedAt',
    'uploadId',
    'uuid',
  ] as const
  $columns = TranscriptionSchema.$columns
  @column.dateTime()
  declare createdAt: DateTime | null
  @column()
  declare language: string
  @column()
  declare meetingId: string | null
  @column()
  declare provider: string | null
  @column()
  declare status: string
  @column()
  declare tenantId: string | null
  @column()
  declare text: string | null
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column()
  declare uploadId: string | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class SummarySchema extends BaseModel {
  static $columns = [
    'actions',
    'createdAt',
    'keyPoints',
    'meetingId',
    'provider',
    'status',
    'summary',
    'tenantId',
    'updatedAt',
    'uuid',
  ] as const
  $columns = SummarySchema.$columns
  @column()
  declare actions: any | null
  @column.dateTime()
  declare createdAt: DateTime | null
  @column()
  declare keyPoints: any | null
  @column()
  declare meetingId: string | null
  @column()
  declare provider: string | null
  @column()
  declare status: string
  @column()
  declare summary: string | null
  @column()
  declare tenantId: string | null
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
}

export class UserHasRoleSchema extends BaseModel {
  static $columns = ['roleId', 'userId'] as const
  $columns = UserHasRoleSchema.$columns
  @column()
  declare roleId: string | null
  @column({ isPrimary: true })
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = [
    'color',
    'companyName',
    'createdAt',
    'email',
    'firstName',
    'lastName',
    'locale',
    'password',
    'phone',
    'status',
    'tenantId',
    'updatedAt',
    'uuid',
    'verified',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare color: string
  @column()
  declare companyName: string | null
  @column.dateTime()
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column()
  declare lastName: string | null
  @column()
  declare locale: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare phone: string | null
  @column()
  declare status: string | null
  @column()
  declare tenantId: string
  @column.dateTime()
  declare updatedAt: DateTime | null
  @column({ isPrimary: true })
  declare uuid: string
  @column()
  declare verified: boolean
}
